name: ogre
description: "AI assistant for your desktop."
publish_to: 'none'
repository: https://github.com/DominikStarke/ogre/
issue_tracker: https://github.com/DominikStarke/ogre/issues

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  keypress_simulator: ^0.2.0
  tray_manager: ^0.3.0
  window_manager: ^0.4.2
  hotkey_manager: ^0.2.3

  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_ai_toolkit: ^0.6.7
  flutter_ai_providers:
    path: ./packages/third_party/flutter_ai_community/packages/flutter_ai_providers
  flutter_markdown: ^0.7.4+3 # fulfill trailing dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/app_icon.png
    