name: ogre
description: "AI assistant for your desktop."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  keypress_simulator: ^0.2.0
  tray_manager: ^0.3.0
  window_manager: ^0.4.2
  hotkey_manager: ^0.2.3

  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_ai_toolkit:
    git:
      url: https://github.com/flutter/ai.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  assets:
    - .env
    - assets/app_icon.png
    